<?php
/**
 * 2013 - COPYRIGHT_YEAR Payplug SAS.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@payplug.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PayPlug module to newer
 * versions in the future.
 *
 * @author    Payplug SAS
 * @copyright 2013 - COPYRIGHT_YEAR Payplug SAS
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *  International Registered Trademark & Property of Payplug SAS
 *
 * This file has been @generated by a phing task by {@link BuildMetadataPHPFromXml}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

return [
    'generalDesc' => [
        'NationalNumberPattern' => '[1369]\\d{2,4}',
        'PossibleLength' => [
            0 => 3,
            1 => 4,
            2 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'tollFree' => [
        'NationalNumberPattern' => '112|999',
        'ExampleNumber' => '112',
        'PossibleLength' => [
            0 => 3,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'premiumRate' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'emergency' => [
        'NationalNumberPattern' => '112|999',
        'ExampleNumber' => '112',
        'PossibleLength' => [
            0 => 3,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'shortCode' => [
        'NationalNumberPattern' => '1(?:0[01348]|1(?:[02]|1[128]|311)|2(?:0[125]|[13-6]|2\\d{0,2})|(?:3[1-35-79]|7[45])\\d\\d?|5(?:454|5\\d\\d?|77|888|999?)|8(?:18?|2|8[18])|9(?:[124]\\d?|68|71|9[0679]))|66628|99[1-469]|13[5-7]|(?:1(?:0[569]|309|5[12]|7[136-9]|9[03])|3[23679]\\d\\d)\\d',
        'ExampleNumber' => '100',
        'PossibleLength' => [
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'standardRate' => [
        'NationalNumberPattern' => '666\\d\\d',
        'ExampleNumber' => '66600',
        'PossibleLength' => [
            0 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'carrierSpecific' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'smsServices' => [
        'NationalNumberPattern' => '(?:3[23679]\\d|666)\\d\\d',
        'ExampleNumber' => '32000',
        'PossibleLength' => [
            0 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'id' => 'MY',
    'countryCode' => 0,
    'internationalPrefix' => '',
    'sameMobileAndFixedLinePattern' => false,
    'numberFormat' => [
    ],
    'intlNumberFormat' => [
    ],
    'mainCountryForCode' => false,
    'leadingZeroPossible' => false,
    'mobileNumberPortableRegion' => false,
];
