<?php
/**
 * 2013 - COPYRIGHT_YEAR Payplug SAS.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0).
 * It is available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@payplug.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PayPlug module to newer
 * versions in the future.
 *
 * @author    Payplug SAS
 * @copyright 2013 - COPYRIGHT_YEAR Payplug SAS
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *  International Registered Trademark & Property of Payplug SAS
 *
 * This file has been @generated by a phing task by {@link BuildMetadataPHPFromXml}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

return [
    'generalDesc' => [
        'NationalNumberPattern' => '[15]\\d{2,5}',
        'PossibleLength' => [
            0 => 3,
            1 => 4,
            2 => 5,
            3 => 6,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'tollFree' => [
        'NationalNumberPattern' => '1(?:1(?:2|6[01]\\d\\d)|2[7-9]|3[15]|41)',
        'ExampleNumber' => '112',
        'PossibleLength' => [
            0 => 3,
            1 => 6,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'premiumRate' => [
        'NationalNumberPattern' => '5\\d{4}',
        'ExampleNumber' => '50000',
        'PossibleLength' => [
            0 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'emergency' => [
        'NationalNumberPattern' => '1(?:12|2[7-9])',
        'ExampleNumber' => '112',
        'PossibleLength' => [
            0 => 3,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'shortCode' => [
        'NationalNumberPattern' => '1(?:1(?:6(?:000|1(?:06|11|23))|8\\d\\d)|65\\d|89[12])|5\\d{4}|1(?:[1349]\\d|2[2-9])',
        'ExampleNumber' => '110',
        'PossibleLength' => [
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'standardRate' => [
        'PossibleLength' => [
            0 => -1,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'carrierSpecific' => [
        'NationalNumberPattern' => '123',
        'ExampleNumber' => '123',
        'PossibleLength' => [
            0 => 3,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'smsServices' => [
        'NationalNumberPattern' => '131|5\\d{4}',
        'ExampleNumber' => '131',
        'PossibleLength' => [
            0 => 3,
            1 => 5,
        ],
        'PossibleLengthLocalOnly' => [
        ],
    ],
    'id' => 'AL',
    'countryCode' => 0,
    'internationalPrefix' => '',
    'sameMobileAndFixedLinePattern' => false,
    'numberFormat' => [
    ],
    'intlNumberFormat' => [
    ],
    'mainCountryForCode' => false,
    'leadingZeroPossible' => false,
    'mobileNumberPortableRegion' => false,
];
