<?php

define('PAYPLUG_TEST_VERSION', '2019-08-06');
define('PAYPLUG_TEST_ONEY_MIN', '100');
define('PAYPLUG_TEST_ONEY_MAX', '3000');
define('PAYPLUG_TEST_EURO_ID', '1');
define('PAYPLUG_TEST_EURO_ISO', 'EUR');
define('PAYPLUG_TEST_DEFAULT_COUNTRY', 'FR');

