<?php

namespace PayPlug\tests\models\classes\Translation;

/**
 * @group unit
 * @group classes
 * @group translation_classes
 *
 * @runTestsInSeparateProcesses
 */
class getTranslationsTest extends BaseTranslation
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->classe
            ->shouldReceive('l')
            ->andReturnUsing(function ($str) {
                return $str;
            });
    }

    public function testIfCardTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getCardTranslations())
            && !empty($this->classe->getCardTranslations())
        );
    }

    public function testIfFooterTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getFooterTranslations())
            && !empty($this->classe->getFooterTranslations())
        );
    }

    public function testIfFrontIntegratedPaymentTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getFrontIntegratedPaymentTranslations())
            && !empty($this->classe->getFrontIntegratedPaymentTranslations())
        );
    }

    public function testIfHeaderTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getHeaderTranslations())
            && !empty($this->classe->getHeaderTranslations())
        );
    }

    public function testIfLoggedTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getLoggedTranslations())
            && !empty($this->classe->getLoggedTranslations())
        );
    }

    public function testIfLoginTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getLoginTranslations())
            && !empty($this->classe->getLoginTranslations())
        );
    }

    public function testIfModalTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getModalTranslations())
            && !empty($this->classe->getModalTranslations())
        );
    }

    public function testIfOrderTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getOrderTranslations())
            && !empty($this->classe->getOrderTranslations())
        );
    }

    public function testIfOrderStateActionRenderTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getOrderStateActionRenderTranslations())
            && !empty($this->classe->getOrderStateActionRenderTranslations())
        );
    }

    public function testIfPaylaterTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getPaylaterTranslations())
            && !empty($this->classe->getPaylaterTranslations())
        );
    }

    public function testIfPaymentMethodsTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getPaymentMethodsTranslations())
            && !empty($this->classe->getPaymentMethodsTranslations())
        );
    }

    public function testIfRequirementsTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getRequirementsTranslations())
            && !empty($this->classe->getRequirementsTranslations())
        );
    }

    public function testIfSubscribeTranslations()
    {
        $this->assertTrue(
            is_array($this->classe->getSubscribeTranslations())
            && !empty($this->classe->getSubscribeTranslations())
        );
    }
}
