<?php

namespace PayPlug\tests\utilities\services\API;

/**
 * @group unit
 * @group service
 * @group api_service
 *
 * @runTestsInSeparateProcesses
 */
class GetRegisterUrlTest extends BaseApi
{
    public $callback_uri;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->callback_uri = 'callback.uri.com';
    }

    /**
     * @dataProvider invalidStringFormatDataProvider
     *
     * @param mixed $callback_uri
     */
    public function testWhenGivenCallBackUriIsntValidString($callback_uri)
    {
        $this->assertSame(
            [
                'result' => false,
                'code' => null,
                'message' => 'Wrong $callback_uri given',
            ],
            $this->service->getRegisterUrl($callback_uri)
        );
    }

    public function testWhenBadRequestExceptionIsThrown()
    {
        $this->authentication
            ->shouldReceive('getRegisterUrl')
            ->andThrow(new \Exception('An error occured during the process', 500));

        $this->assertSame(
            [
                'result' => false,
                'code' => 500,
                'message' => 'An error occured during the process',
            ],
            $this->service->getRegisterUrl($this->callback_uri)
        );
    }

    public function testWhenRegisterUrlIsGot()
    {
        $this->authentication->shouldReceive([
            'getRegisterUrl' => $this->callback_uri,
        ]);
        $this->assertSame(
            [
                'result' => true,
                'code' => 200,
                'redirection' => $this->callback_uri,
            ],
            $this->service->getRegisterUrl($this->callback_uri)
        );
    }
}
