version: '3'
services:
  presta_2:
    image: prestashop/prestashop:1.6-5.6-apache
    volumes:
      - ../:/var/www/html/modules/payplug
    environment:
      - PS_DEV_MODE=1
      - DB_NAME=prestashop
      - DB_SERVER=database_2
      - PS_DOMAIN=localhost:8011
      - PS_INSTALL_AUTO=1
      - ADMIN_MAIL=admin@example.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - PS_LANGUAGE=fr
      - PS_COUNTRY=FR
    ports:
      - "8011:80"
    depends_on:
      - database_2
    links:
       - database_2
  phpmyadmin_2:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database_2
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 8012:80
    depends_on:
      - database_2
  database_2:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=ps_user
      - MYSQL_PASSWORD=admin
    expose:
      - 3308
    ports:
      - "3308:3306"
