version: '3'
services:
  presta:
    image: prestashop/prestashop:1.7.7-7.3
    volumes:
      - ../:/var/www/html/modules/payplug
    environment:
      - PS_DEV_MODE=1
      - DB_NAME=prestashop
      - DB_SERVER=database
      - PS_DOMAIN=localhost:8001
      - PS_INSTALL_AUTO=1
      - ADMIN_MAIL=admin@example.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=admin-dev
      - PS_LANGUAGE=fr
      - PS_COUNTRY=FR
    ports:
      - "8001:80"
    depends_on:
      - database
    links:
       - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 8002:80
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=ps_user
      - MYSQL_PASSWORD=admin
    expose:
      - 3306
    ports:
      - "3306:3306"
